spring:
  application:
    name: FocusMind AI - Smart Study Planner
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/focusmind}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      base-url: https://integrate.api.nvidia.com/v1
      api-key: ${NVIDIA_API_KEY}
      chat:
        options:
          model: meta/llama-3.1-8b-instruct

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 1 day
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
